<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns="http://maven.apache.org/POM/4.0.0"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>de.binaerebauten.gleichklang</groupId>
		<artifactId>gleichklang-parent</artifactId>
		<version>0.0.1-SNAPSHOT</version>
		<relativePath>../</relativePath>
	</parent>

	<artifactId>member-web</artifactId>
	<packaging>war</packaging>

	<build>
		<!-- this changes the name of the WAR file, which is used during deployment as context path -->
		<finalName>Gleichklang</finalName>

		<plugins>
			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>build-helper-maven-plugin</artifactId>
				<executions>
					<execution>
						<phase>pre-integration-test</phase>
						<id>reserve-network-port</id>
						<goals>
							<goal>reserve-network-port</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.codehaus.cargo</groupId>
				<artifactId>cargo-maven2-plugin</artifactId>
				<executions>
					<execution>
						<id>start-container</id>
						<phase>pre-integration-test</phase>
						<goals>
							<goal>start</goal>
						</goals>
					</execution>
					<execution>
						<id>stop-container</id>
						<phase>post-integration-test</phase>
						<goals>
							<goal>stop</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-failsafe-plugin</artifactId>
				<executions>
					<execution>
						<id>run-integration-tests</id>
						<phase>integration-test</phase>
						<goals>
							<goal>integration-test</goal>
						</goals>
						<configuration>
							<systemProperties>
								<test.base.url>
									http://localhost:${http.port}${app.context.path}
								</test.base.url>
							</systemProperties>
						</configuration>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>

	<dependencies>
		<dependency>
			<groupId>de.binaerebauten.gleichklang</groupId>
			<artifactId>core</artifactId>
			<version>${project.version}</version>
		</dependency>

		<!-- test dependencies -->
		<dependency>
			<groupId>de.binaerebauten.gleichklang</groupId>
			<artifactId>core</artifactId>
			<version>${project.version}</version>
			<type>test-jar</type>
			<scope>test</scope>
		</dependency>

		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-test</artifactId>
		</dependency>

		<dependency>
			<groupId>org.mockito</groupId>
			<artifactId>mockito-all</artifactId>
		</dependency>

		<!-- H2 in memory database -->
		<dependency>
			<groupId>com.h2database</groupId>
			<artifactId>h2</artifactId>
		</dependency>


		<dependency>
			<groupId>org.apache.tomcat</groupId>
			<artifactId>tomcat-jdbc</artifactId>
			<!--
                Marked as optional since tomcat already provides this jar.
                This prevents that this jar is copied to the resulting war file.

                This dependency is repeated here so that running in embedded mode
                via idea works.
            -->
			<optional>true</optional>
		</dependency>

		<!-- embed TOMCAT, marked as optional to avoid packaging it in the war
			file -->
		<dependency>
			<groupId>org.apache.tomcat.embed</groupId>
			<artifactId>tomcat-embed-core</artifactId>
			<optional>true</optional>
		</dependency>
		<dependency>
			<groupId>org.apache.tomcat.embed</groupId>
			<artifactId>tomcat-embed-logging-juli</artifactId>
			<optional>true</optional>
		</dependency>
		<dependency>
			<groupId>org.apache.tomcat.embed</groupId>
			<artifactId>tomcat-embed-jasper</artifactId>
			<optional>true</optional>
		</dependency>
		<dependency>
			<groupId>org.apache.tomcat.embed</groupId>
			<artifactId>tomcat-embed-websocket</artifactId>
			<optional>true</optional>
		</dependency>
		<!-- Email -->
		<dependency>
			<groupId>javax.mail</groupId>
			<artifactId>mail</artifactId>
		</dependency>

		<dependency>
			<groupId>com.vaadin</groupId>
			<artifactId>vaadin-themes</artifactId>
		</dependency>

		<dependency>
			<groupId>commons-fileupload</groupId>
			<artifactId>commons-fileupload</artifactId>
			<version>1.3.1</version>
		</dependency>

	</dependencies>

	<profiles>
		<profile>
			<id>production</id>
            <activation>
                <activeByDefault>true</activeByDefault>
            </activation>
			<build>
				<plugins>
					<plugin>
						<groupId>com.vaadin</groupId>
						<artifactId>vaadin-maven-plugin</artifactId>
						<version>${vaadin.version}</version>
						<executions>
							<execution>
								<goals>
									<goal>clean</goal>
									<goal>resources</goal>
									<goal>update-theme</goal>
									<goal>update-widgetset</goal>
									<goal>compile-theme</goal>
									<goal>compile</goal>
								</goals>
							</execution>
						</executions>
						<configuration>
							<theme>gk_theme</theme>
						</configuration>
					</plugin>
					<plugin>
						<groupId>org.codehaus.mojo</groupId>
						<artifactId>exec-maven-plugin</artifactId>
						<version>1.6.0</version>
						<configuration>
							<mainClass>com.vaadin.sass.SassCompiler</mainClass>
							<arguments>
								<argument>
									${project.basedir}/src/main/webapp/VAADIN/themes/gk_theme/heidelpay_hco.scss
								</argument>
								<argument>${project.basedir}/src/main/webapp/VAADIN/themes/gk_theme/heidelpay_hco.css</argument>
							</arguments>
						</configuration>
						<executions>
							<execution>
								<goals>
									<goal>java</goal>
								</goals>
								<phase>process-resources</phase>
							</execution>
						</executions>
					</plugin>
				</plugins>
			</build>
		</profile>
	</profiles>
</project>