# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.synced_folder ".", "/vagrant"

  config.vm.network "forwarded_port", guest: 3306, host: 3306
  config.vm.network "forwarded_port", guest: 3310, host: 3310

  config.vm.provision "shell", path: "mysql/setup_mysql.sh", privileged: false
  config.vm.provision "shell", path: "clamav/setup_clamav.sh", privileged: false

  config.vm.provider "virtualbox" do |v|
    v.memory = 2560
  end
end
