CREATE TABLE question_choice_group_name (
  question VARCHAR(255),
  choice_group VARCHAR(1024)
);
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('partner.p_region', 'INTERNATIONAL;Ganze EU;Ganz Deutschland;Ganz Österreich;Ganze Schweiz;Deutschland: Baden-W;Deutschland: Bayern;Deutschland: Berlin;Deutschland: Branden;Deutschland: Bremen;Deutschland: Hamburg;Deutschland: Hessen;Deutschland:');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('freund.f_region', 'INTERNATIONAL;Ganze EU;Ganz Deutschland;Ganz Österreich;Ganze Schweiz;Deutschland: Baden-W;Deutschland: Bayern;Deutschland: Berlin;Deutschland: Branden;Deutschland: Bremen;Deutschland: Hamburg;Deutschland: Hessen;Deutschland:');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('partner.p_land_1', 'Deutschland (DE);Österreich (AT);Schweiz (CH)');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('partner.p_land_2', 'Deutschland (DE);Österreich (AT);Schweiz (CH)');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('partner.p_land_3', 'Deutschland (DE);Österreich (AT);Schweiz (CH)');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('freund.f_land_1', 'Deutschland (DE);Österreich (AT);Schweiz (CH)');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('freund.f_land_2', 'Deutschland (DE);Österreich (AT);Schweiz (CH)');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('freund.f_land_3', 'Deutschland (DE);Österreich (AT);Schweiz (CH)');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('partner.p_radius_1', 'Umkreis');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('partner.p_radius_2', 'Umkreis');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('partner.p_radius_3', 'Umkreis');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('freund.f_radius_1', 'Umkreis');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('freund.f_radius_2', 'Umkreis');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('freund.f_radius_3', 'Umkreis');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('partner.heiraten', 'Standard-Typus');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('partner.umzug', 'Standard-Typus');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('partner.wochenende', 'Standard-Typus');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('partner.p_raucher_akzeptieren', 'Standard-Typus');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('partner.p_gewicht_akzeptieren', 'Standard-Typus');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('partner.p_hiv', 'Standard-Typus');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('partner.p_sexfunc', 'Standard-Typus');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('partner.p_behinderung', 'Standard-Typus');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('partner.p_erkrankung_koer', 'Standard-Typus');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('partner.p_erkrankung_psy', 'Standard-Typus');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('partner.p_bisex_suche', 'Standard-Typus');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('partner.p_transsex_suche', 'Standard-Typus');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('partner.p_intersex_suche', 'Standard-Typus');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('partner.p_sexfunc_suche', 'Standard-Typus');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('partner.p_behinderung_suche', 'Standard-Typus');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('partner.p_erkrankung_koer_suche', 'Standard-Typus');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('partner.p_erkrankung_psy_suche', 'Standard-Typus');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('partner.p_hiv_suche', 'Standard-Typus');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('partner.p_hochsensibel', 'Standard-Typus');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('partner.p_kuenstler_suche', 'Standard-Typus');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('partner.p_akad_suche', 'Standard-Typus');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('partner.p_oeko_praef', 'Standard-Typus');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('partner.p_eso_praef', 'Standard-Typus');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('partner.p_tierrechte_praef', 'Standard-Typus');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('partner.p_fkk_praef', 'Standard-Typus');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('partner.p_relsearch_ch', 'Standard-Typus');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('partner.p_relsearch_is', 'Standard-Typus');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('partner.p_relsearch_jud', 'Standard-Typus');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('partner.p_relsearch_bud', 'Standard-Typus');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('partner.p_relsearch_hin', 'Standard-Typus');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('partner.p_relsearch_schin', 'Standard-Typus');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('partner.p_relsearch_bahai', 'Standard-Typus');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('partner.p_relsearch_eso', 'Standard-Typus');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('partner.p_relsearch_agn', 'Standard-Typus');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('partner.p_tierakz_hu', 'Standard-Typus');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('partner.p_tierakz_ka', 'Standard-Typus');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('partner.p_tierakz_na', 'Standard-Typus');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('partner.p_tierakz_pf', 'Standard-Typus');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('partner.p_tierakz_vo', 'Standard-Typus');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('partner.p_tierakz_fi', 'Standard-Typus');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('partner.p_tierakz_re', 'Standard-Typus');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('partner.p_tierakz_in', 'Standard-Typus');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('freund.f_raucher_akzeptieren', 'Standard-Typus');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('freund.f_hiv', 'Standard-Typus');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('freund.f_behinderung', 'Standard-Typus');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('freund.f_erkrankung_koer', 'Standard-Typus');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('freund.f_erkrankung_psy', 'Standard-Typus');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('freund.f_behinderung_suche', 'Standard-Typus');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('freund.f_erkrankung_koer_suche', 'Standard-Typus');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('freund.f_erkrankung_psy_suche', 'Standard-Typus');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('freund.f_hiv_suche', 'Standard-Typus');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('freund.f_hochsensibel', 'Standard-Typus');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('freund.f_kuenstler_suche', 'Standard-Typus');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('freund.f_akad_suche', 'Standard-Typus');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('freund.f_oeko_praef', 'Standard-Typus');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('freund.f_eso_praef', 'Standard-Typus');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('freund.f_tierrechte_praef', 'Standard-Typus');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('freund.f_fkk_praef', 'Standard-Typus');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('freund.f_relsearch_ch', 'Standard-Typus');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('freund.f_relsearch_is', 'Standard-Typus');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('freund.f_relsearch_jud', 'Standard-Typus');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('freund.f_relsearch_bud', 'Standard-Typus');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('freund.f_relsearch_hin', 'Standard-Typus');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('freund.f_relsearch_schin', 'Standard-Typus');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('freund.f_relsearch_bahai', 'Standard-Typus');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('freund.f_relsearch_eso', 'Standard-Typus');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('freund.f_relsearch_agn', 'Standard-Typus');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('freund.f_tierakz_hu', 'Standard-Typus');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('freund.f_tierakz_ka', 'Standard-Typus');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('freund.f_tierakz_na', 'Standard-Typus');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('freund.f_tierakz_pf', 'Standard-Typus');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('freund.f_tierakz_vo', 'Standard-Typus');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('freund.f_tierakz_fi', 'Standard-Typus');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('freund.f_tierakz_re', 'Standard-Typus');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('freund.f_tierakz_in', 'Standard-Typus');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('person.relprev_ch', 'Standard-Typus');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('person.relprev_is', 'Standard-Typus');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('person.relprev_jud', 'Standard-Typus');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('person.relprev_bud', 'Standard-Typus');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('person.relprev_hin', 'Standard-Typus');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('person.relprev_schin', 'Standard-Typus');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('person.relprev_bahai', 'Standard-Typus');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('person.relprev_eso', 'Standard-Typus');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('person.relprev_agn', 'Standard-Typus');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('partner.kinderwunsch', 'Kinderwunsch');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('partner.p_platonisch_suche', 'Platonisch');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('partner.p_sexdev', 'Sex-Bedeutung');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('partner.p_bdsm_suche', 'BDSM-Initial');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('partner.p_bdsm_suche_allg', 'BDSM-Initial');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('freund.f_bdsm_suche', 'BDSM-Initial');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('freund.f_bdsm_suche_allg', 'BDSM-Initial');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('partner.p_bdsm_suche_spezial', 'Partner/in sollte de;Partner/in sollte do');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('freund.f_bdsm_suche_spezial', 'Partner/in sollte de;Partner/in sollte do');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('partner.p_akz_fem_mask', 'Feminität');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('partner.p_gewicht_ausschluss', 'Figur');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('partner.p_gewicht_wunsch', 'Figur');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('partner.p_dreierbez', 'Spezial-Ausschließlich');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('partner.p_bisex', 'Spezial-Ausschließlich');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('partner.p_transsex', 'Spezial-Ausschließlich');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('partner.p_intersex', 'Spezial-Ausschließlich');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('partner.p_transvestit', 'Spezial-Ausschließlich');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('partner.p_erotik', 'Erotik-Abfrage (P)');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('partner.p_alleinerziehend_select', 'Drei-Stufung (mit unentschieden)');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('freund.f_alleinerziehend_select', 'Drei-Stufung (mit unentschieden)');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('partner.p_vege_suche', 'Vegetarier-Vegan');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('partner.p_vegan_suche', 'Vegetarier-Vegan');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('freund.f_vege_suche', 'Vegetarier-Vegan');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('freund.f_vegan_suche', 'Vegetarier-Vegan');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('partner.p_fwunsch_fussball', 'Drei-Stufung (ja/nein)');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('partner.p_fwunsch_motorsport', 'Drei-Stufung (ja/nein)');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('partner.p_fwunsch_auto', 'Drei-Stufung (ja/nein)');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('partner.p_fwunsch_motorrad', 'Drei-Stufung (ja/nein)');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('partner.p_fwunsch_computer', 'Drei-Stufung (ja/nein)');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('freund.f_fwunsch_fussball', 'Drei-Stufung (ja/nein)');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('freund.f_fwunsch_motorsport', 'Drei-Stufung (ja/nein)');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('freund.f_fwunsch_auto', 'Drei-Stufung (ja/nein)');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('freund.f_fwunsch_motorrad', 'Drei-Stufung (ja/nein)');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('freund.f_fwunsch_computer', 'Drei-Stufung (ja/nein)');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('partner.p_fakz_fussball', 'auf keinen Fall;eher nicht;unentschieden;eher ja;auf jeden Fall');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('partner.p_fakz_motorsport', 'auf keinen Fall;eher nicht;unentschieden;eher ja;auf jeden Fall');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('partner.p_fakz_auto', 'auf keinen Fall;eher nicht;unentschieden;eher ja;auf jeden Fall');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('partner.p_fakz_motorrad', 'auf keinen Fall;eher nicht;unentschieden;eher ja;auf jeden Fall');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('partner.p_fakz_computer', 'auf keinen Fall;eher nicht;unentschieden;eher ja;auf jeden Fall');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('freund.f_fakz_fussball', 'auf keinen Fall;eher nicht;unentschieden;eher ja;auf jeden Fall');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('freund.f_fakz_motorsport', 'auf keinen Fall;eher nicht;unentschieden;eher ja;auf jeden Fall');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('freund.f_fakz_auto', 'auf keinen Fall;eher nicht;unentschieden;eher ja;auf jeden Fall');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('freund.f_fakz_motorrad', 'auf keinen Fall;eher nicht;unentschieden;eher ja;auf jeden Fall');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('freund.f_fakz_computer', 'auf keinen Fall;eher nicht;unentschieden;eher ja;auf jeden Fall');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('freund.f_reise_partner', 'Nein-Auch-Nur');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('freund.f_gay_select', 'Nein-Auch-Nur');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('freund.f_erotik', 'Erotik-Abfrage (F)');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('ptext.frage1', 'Satzanfänge');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('ptext.frage2', 'Satzanfänge');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('ptext.frage3', 'Satzanfänge');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('ftext.frage1', 'Satzanfänge');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('ftext.frage2', 'Satzanfänge');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('ftext.frage3', 'Satzanfänge');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('aussehen.figur', 'Eigene Figur');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('aussehen.koerpertyp', 'Eigener Körpertyp');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('aussehen.haarfarbe', 'Eigene Haarfarbe');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('aussehen.haarlaenge', 'Eigene Haarlänge');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('aussehen.glatze', 'Eigene Glatze');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('aussehen.haartyp', 'Eigener Haartyp');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('aussehen.augenfarbe', 'Eigene Augenfarbe');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('aussehen.brille', 'Eigene Brille');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('aussehen.bart', 'Eigener Bart');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('aussehen.brustbehaarung', 'Eigene Behaarung');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('aussehen.koerperbehaarung', 'Eigene Behaarung');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('aussehen.fem_mask', 'Eigene Feminität/Maskulinität');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('person.schulabschluss', 'Schulabschluss');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('person.berufsausbildung', 'Ausbildung');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('person.beruflicher_status', 'Berufsstatus');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('person.berufsfeld', 'Berufsfeld');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('person.familienstand', 'Familienstand');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('person.kinder_haushalt', 'Drei-Stufung (teils)');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('person.tiere', 'Eigene Tiere');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('person.rauchen', 'Rauchen');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('person.alkoholkonsum', 'Alkohol');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('person.schlafrhythmus', 'Schlafrythmus');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('person.ordnungsliebe', 'Vier-Stufung (ja/nein)');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('person.vege_info', 'Eigen Vegetarismus');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('person.vegan_info', 'Eigen Vegetarismus');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('person.hochsensibel_info', 'Fünf-Stufung (mit unbekannt)');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('hobby_v.fernsehen', 'Hobby Fernsehen');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('hobby_v.musik_passiv', 'Hobby Musik (passiv)');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('hobby_v.musik_aktiv', 'Hobby Musik (aktiv)');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('hobby_v.bildung', 'Bildungsinteressen');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('hobby_v.computer', 'Hobby Interessen Computer');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('hobby_v.essen_kueche', 'Hobby Essen Küche');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('hobby_v.essen_kost', 'Hobby Essen Kost');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('hobby_v.geselligkeit', 'Hobby Geselligkeit');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('hobby_v.heimwerken', 'Hobby Heimwerken');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('hobby_v.gestaltende_kunst', 'Hobby Gestaltende Kunst');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('hobby_v.darstellende_kunst', 'Hobby Darstellende Kunst');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('hobby_v.foto_film', 'Hobby Foto/Film');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('hobby_v.handarbeit', 'Hobby Handarbeit');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('hobby_v.mode', 'Hobby Mode');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('hobby_v.kulturveranstaltungen', 'Hobby Kulturveranstaltungen');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('hobby_v.spiele', 'Hobby Spiele');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('hobby_v.literatur_gattung', 'Hobby Literatur Gattung');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('hobby_v.literatur_themen', 'Hobby Literatur Themen');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('hobby_v.tanzen', 'Hobby Tanzen');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('hobby_v.gesundheit', 'Hobby Gesundheit');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('hobby_v.sport_aktiv', 'Hobby Sport');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('hobby_v.sport_passiv', 'Hobby Sport');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('hobby_v.technik', 'Hobby Technik');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('hobby_v.tiere_natur', 'Hobby Tiere/Natur');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('hobby_v.extremsport', 'Hobby Extremsport');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('hobby_v.soziales_engagement', 'Hobby Engagement Sozial');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('hobby_v.politisches_engagement', 'Hobby Engagement Politisch');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('hobby_v.kommunikation', 'Hobby Kommunikation');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('hobby_v.sammeln', 'Hobby Sammeln');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('hobby_v.geld', 'Hobby Geld');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('hobby_v.esoterik', 'Hobby Esoterik');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('hobby_v.reisen', 'Hobby Reisen');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('partner.p_hiv_select', 'Ja/Nein');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('partner.p_behinderten_select', 'Ja/Nein');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('partner.p_koerperkrank_select', 'Ja/Nein');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('partner.p_psychischkrank_select', 'Ja/Nein');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('partner.p_nur_foto', 'Ja/Nein');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('partner.p_bdsm_nur', 'Ja/Nein');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('partner.p_platonisch_mitteil', 'Ja/Nein');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('partner.p_bdsm_mitteil', 'Ja/Nein');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('partner.p_erotik_mitteil', 'Ja/Nein');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('freund.f_bdsm_nur', 'Ja/Nein');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('freund.f_hiv_select', 'Ja/Nein');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('freund.f_behinderten_select', 'Ja/Nein');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('freund.f_koerperkrank_select', 'Ja/Nein');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('freund.f_psychischkrank_select', 'Ja/Nein');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('freund.f_nur_foto', 'Ja/Nein');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('freund.f_gay_mitteil', 'Ja/Nein');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('freund.f_bdsm_mitteil', 'Ja/Nein');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('freund.f_erotik_mitteil', 'Ja/Nein');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('person.alleinerziehend', 'Ja/Nein');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('person.in_partnerschaft', 'Ja/Nein');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('person.kuenstler', 'Ja/Nein');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('person.transvestit', 'Ja/Nein');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('person.hochsensibel_mitteil', 'Ja/Nein');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('person.rel_mitteil', 'Ja/Nein');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('person.hiv_info', 'Ja/Nein');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('person.behinderten_info', 'Ja/Nein');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('person.koerperkrank_info', 'Ja/Nein');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('person.psychisch_krank_info', 'Ja/Nein');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('stamm.geschlecht', 'Geschlecht Auswahl');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('partner.geschlecht', 'Geschlecht Suche');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('freund.geschlecht', 'Geschlecht Suche');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('partnerschaft.p5_1', 'Affinity_choices');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('partnerschaft.p17_2', 'Affinity_choices');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('partnerschaft.p31_1', 'Affinity_choices');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('partnerschaft.p31_2', 'Affinity_choices');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('partnerschaft.p17_3', 'Affinity_choices');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('partnerschaft.p1_4', 'Affinity_choices');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('partnerschaft.p31_3', 'Affinity_choices');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('partnerschaft.p10_4', 'Affinity_choices');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('partnerschaft.p11_4', 'Affinity_choices');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('partnerschaft.p16_4', 'Affinity_choices');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('partnerschaft.p5_5', 'Affinity_choices');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('partnerschaft.p13_5', 'Affinity_choices');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('partnerschaft.p17_5', 'Affinity_choices');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('partnerschaft.p1_6', 'Affinity_choices');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('partnerschaft.p11_6', 'Affinity_choices');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('partnerschaft.p5_7', 'Affinity_choices');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('partnerschaft.p12_6', 'Affinity_choices');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('partnerschaft.p14_7', 'Affinity_choices');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('partnerschaft.p16_7', 'Affinity_choices');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('partnerschaft.p31_4', 'Affinity_choices');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('partnerschaft.p5_8', 'Affinity_choices');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('partnerschaft.p6_8', 'Affinity_choices');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('partnerschaft.p17_8', 'Affinity_choices');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('partnerschaft.p31_5', 'Affinity_choices');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('partnerschaft.p12_11', 'Affinity_choices');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('gesellschaft.g1_1', 'Affinity_choices');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('gesellschaft.g2_1', 'Affinity_choices');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('gesellschaft.g4_1', 'Affinity_choices');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('gesellschaft.g5_1', 'Affinity_choices');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('gesellschaft.g2_3', 'Affinity_choices');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('gesellschaft.g1_5', 'Affinity_choices');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('gesellschaft.g5_5', 'Affinity_choices');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('gesellschaft.g3_6', 'Affinity_choices');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('gesellschaft.g1_7', 'Affinity_choices');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('gesellschaft.g3_7', 'Affinity_choices');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('gesellschaft.g4_7', 'Affinity_choices');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('gesellschaft.g2_9', 'Affinity_choices');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('gesellschaft.g3_10', 'Affinity_choices');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('gesellschaft.g5_12', 'Affinity_choices');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('gesellschaft.g4_12', 'Affinity_choices');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('persoenlichkeit.pk_36_ve', 'Affinity_choices');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('persoenlichkeit.pk_37_h', 'Affinity_choices');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('persoenlichkeit.pk_38_ge', 'Affinity_choices');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('persoenlichkeit.pk_43_fa', 'Affinity_choices');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('persoenlichkeit.pk_62_r', 'Affinity_choices');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('persoenlichkeit.pk_64_sb', 'Affinity_choices');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('persoenlichkeit.pk_67_h', 'Affinity_choices');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('persoenlichkeit.pk_68_ge', 'Affinity_choices');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('persoenlichkeit.pk_72_pe', 'Affinity_choices');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('persoenlichkeit.pk_77_i', 'Affinity_choices');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('persoenlichkeit.pk_81_al', 'Affinity_choices');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('persoenlichkeit.pk_88_l', 'Affinity_choices');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('persoenlichkeit.pk_91_ae', 'Affinity_choices');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('persoenlichkeit.pk_92_r', 'Affinity_choices');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('persoenlichkeit.pk_104_aes', 'Affinity_choices');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('persoenlichkeit.pk_107_i', 'Affinity_choices');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('persoenlichkeit.pk_119_s', 'Affinity_choices');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('persoenlichkeit.pk_141_al', 'Affinity_choices');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('persoenlichkeit.pk_163_fa', 'Affinity_choices');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('persoenlichkeit.pk_194_aes', 'Affinity_choices');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('persoenlichkeit.pk_209_s', 'Affinity_choices');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('persoenlichkeit.pk_217_h', 'Affinity_choices');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('persoenlichkeit.pk_230_f', 'Affinity_choices');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('persoenlichkeit.pk_262_e', 'Affinity_choices');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('persoenlichkeit.pk_266_ol', 'Affinity_choices');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('persoenlichkeit.pk_269_s', 'Affinity_choices');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('persoenlichkeit.pk_290_f', 'Affinity_choices');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('persoenlichkeit.pk_292_e', 'Affinity_choices');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('persoenlichkeit.pk_299_s', 'Affinity_choices');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('freundschaft.fd_pp106', 'Affinity_choices');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('freundschaft.fd_sf71', 'Affinity_choices');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('freundschaft.fd_nd119', 'Affinity_choices');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('freundschaft.fd_ag42', 'Affinity_choices');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('freundschaft.fd_ag43', 'Affinity_choices');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('freundschaft.fd_ps53', 'Affinity_choices');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('freundschaft.fd_sf76', 'Affinity_choices');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('freundschaft.fd_pp105', 'Affinity_choices');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('freundschaft.fd_ps50', 'Affinity_choices');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('freundschaft.fd_ps46', 'Affinity_choices');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('freundschaft.fd_sf72', 'Affinity_choices');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('freundschaft.fd_sp129', 'Affinity_choices');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('freundschaft.fd_ag35', 'Affinity_choices');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('freundschaft.fd_pp100', 'Affinity_choices');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('freundschaft.fd_pp111', 'Affinity_choices');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('freundschaft.fd_sf62', 'Affinity_choices');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('freundschaft.fd_ps55', 'Affinity_choices');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('freundschaft.fd_ag34', 'Affinity_choices');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('freundschaft.fd_sp127', 'Affinity_choices');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('freundschaft.fd_ag39', 'Affinity_choices');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('freundschaft.fd_sp130', 'Affinity_choices');
INSERT INTO question_choice_group_name(question, choice_group) VALUES ('source', 'sources');