DROP TABLE IF EXISTS choice_answer;
DROP TABLE IF EXISTS answer;

DROP TABLE IF EXISTS choice;
DROP TABLE IF EXISTS question;
DROP TABLE IF EXISTS choice_group;

DROP TABLE IF EXISTS question_group;
DROP TABLE IF EXISTS questionnaire;

DROP TABLE IF EXISTS i18n;

DROP TABLE IF EXISTS locatable;

CREATE TABLE i18n (
  id          BIGINT(20)   NOT NULL AUTO_INCREMENT,
  legacy_id   VARCHAR(255),
  change_date TIMESTAMP             DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  create_date DATETIME              DEFAULT NULL,
  language    VARCHAR(255),
  i18n_key    VARCHAR(255) NOT NULL,
  i18n_value  TEXT         NOT NULL,
  base_name   VARCHAR(255) NOT NULL DEFAULT 'NONE',
  PRIMARY KEY (id)
);


CREATE INDEX i18n_base_name_language ON i18n (base_name, language);
CREATE INDEX i18n_key_index ON i18n (i18n_key);
CREATE UNIQUE INDEX i18n_language_i18n_key_base_name ON i18n (language, i18n_key, base_name);
CREATE INDEX i18n_legacy_idx ON i18n (legacy_id);

CREATE TABLE questionnaire (
  id                      BIGINT(20)   NOT NULL AUTO_INCREMENT,
  legacy_id               VARCHAR(255),
  change_date             TIMESTAMP             DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  create_date             DATETIME              DEFAULT NULL,
  i18n_key                VARCHAR(255) NOT NULL,
  recommendation_category VARCHAR(255),
  deleted                 BIT(1)       NOT NULL DEFAULT FALSE,
  visible                 BIT(1)       NOT NULL DEFAULT TRUE,
  sort_order              INT(11)      NOT NULL,
  PRIMARY KEY (id)
);

CREATE UNIQUE INDEX questionnaire_i18n_key ON questionnaire (i18n_key);
CREATE UNIQUE INDEX questionnaire_sort_order ON questionnaire (sort_order);

CREATE TABLE question_group (
  id               BIGINT(20)   NOT NULL AUTO_INCREMENT,
  legacy_id        VARCHAR(255),
  change_date      TIMESTAMP             DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  create_date      DATETIME              DEFAULT NULL,
  i18n_key         VARCHAR(255) NOT NULL,
  questionnaire_id BIGINT(20),
  deleted          BIT(1)       NOT NULL DEFAULT FALSE,
  sort_order       INT(11)      NOT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (questionnaire_id) REFERENCES questionnaire (id)
);
CREATE INDEX questionnaire_id_idx ON question_group (questionnaire_id);
CREATE UNIQUE INDEX question_group_i18n_key_questionnaire ON question_group (i18n_key, questionnaire_id);
CREATE UNIQUE INDEX question_group_sort_order_questionnaire ON question_group (sort_order, questionnaire_id);

CREATE TABLE choice_group (
  id          BIGINT(20)   NOT NULL AUTO_INCREMENT,
  legacy_id   VARCHAR(255),
  change_date TIMESTAMP             DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  create_date DATETIME              DEFAULT NULL,
  name        VARCHAR(255) NOT NULL,
  legacy_name VARCHAR(255),
  deleted     BIT(1)       NOT NULL DEFAULT FALSE,
  PRIMARY KEY (id)
);

CREATE TABLE question (
  id                  BIGINT(20)   NOT NULL AUTO_INCREMENT,
  DTYPE               VARCHAR(31)  NOT NULL,
  legacy_id           VARCHAR(255),
  change_date         TIMESTAMP             DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  create_date         DATETIME              DEFAULT NULL,
  label               VARCHAR(255),
  required            BIT(1),
  selection_type      VARCHAR(25),
  max_length          INT(11),
  number_of_lines     INT(11),
  max_value           INT(11),
  min_value           INT(11),
  i18n_key            VARCHAR(255) NOT NULL,
  choice_group_id     BIGINT(20),
  question_group_id   BIGINT(20),
  questionnaire_id    BIGINT(20),
  deleted             BIT(1)       NOT NULL DEFAULT FALSE,
  sort_order          INT(11)      NOT NULL,
  visible             BIT(1)       NOT NULL DEFAULT TRUE,
  representation_type VARCHAR(25)  NOT NULL DEFAULT 'DEFAULT',
  PRIMARY KEY (id),
  FOREIGN KEY (question_group_id) REFERENCES question_group (id),
  FOREIGN KEY (choice_group_id) REFERENCES choice_group (id)
);
CREATE INDEX choice_group_id_idx ON question (choice_group_id);
CREATE INDEX question_group_id_idx ON question (question_group_id);
CREATE UNIQUE INDEX question_i18n_key ON question (i18n_key);
CREATE INDEX question_legacy_id ON question (legacy_id);
CREATE UNIQUE INDEX question_sort_order_question_group ON question (sort_order, question_group_id);


CREATE TABLE choice (
  id              BIGINT(20) NOT NULL AUTO_INCREMENT,
  legacy_id       VARCHAR(255),
  change_date     TIMESTAMP           DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  create_date     DATETIME            DEFAULT NULL,
  sort_order      INT(11)    NOT NULL,
  i18n_key        VARCHAR(255),
  choice          VARCHAR(255),
  choice_group_id BIGINT(20) NOT NULL,
  question_id     BIGINT(20)          DEFAULT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (choice_group_id) REFERENCES choice_group (id)
);
CREATE INDEX choicevalue_i18n_key_index ON choice (i18n_key);
CREATE INDEX choice_group_id_idx ON choice (choice_group_id);
CREATE UNIQUE INDEX choice_sort_order_choice_group ON choice (sort_order, choice_group_id);

CREATE TABLE answer (
  id                 BIGINT(20)  NOT NULL AUTO_INCREMENT,
  DTYPE              VARCHAR(31) NOT NULL,
  legacy_id          VARCHAR(255),
  change_date        TIMESTAMP            DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  create_date        DATETIME             DEFAULT NULL,
  number_value       INT(11),
  text_value         TEXT,
  question_id        BIGINT(20)  NOT NULL,
  user_id            BIGINT(20)  NOT NULL,
  search_relocatable BIT(1)               DEFAULT b'0',
  relocatable        BIT(1)               DEFAULT b'0',
  PRIMARY KEY (id),
  FOREIGN KEY (question_id) REFERENCES question (id)
);
CREATE INDEX answer_legacy_id ON answer (legacy_id);
CREATE INDEX answer_question_id ON answer (question_id);
CREATE INDEX user_id ON answer (user_id);


CREATE TABLE choice_answer (
  answer_id BIGINT(20) NOT NULL,
  choice_id BIGINT(20) NOT NULL,
  PRIMARY KEY (answer_id, choice_id),
  FOREIGN KEY (answer_id) REFERENCES answer (id),
  FOREIGN KEY (choice_id) REFERENCES choice (id)
);

CREATE INDEX choice_id_idx ON choice_answer (choice_id);

CREATE TABLE locatable (
  id          BIGINT(20)  NOT NULL AUTO_INCREMENT,
  DTYPE       VARCHAR(31) NOT NULL,
  legacy_id   VARCHAR(255),
  change_date TIMESTAMP            DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  create_date DATETIME             DEFAULT NULL,
  i18n_key    VARCHAR(255)         DEFAULT NULL,
  zip         VARCHAR(25)          DEFAULT NULL,
  latitude    DOUBLE               DEFAULT NULL,
  longitude   DOUBLE               DEFAULT NULL,
  parent_id   BIGINT(20)           DEFAULT NULL,
  region_name VARCHAR(255)         DEFAULT NULL,
  region_id   BIGINT(20)           DEFAULT NULL,
  sort_order  INT(11)              DEFAULT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (parent_id) REFERENCES locatable (id)
);

CREATE TABLE legacy_choice(
  id              BIGINT(20) NOT NULL AUTO_INCREMENT,
  legacy_id       VARCHAR(255),
  change_date     TIMESTAMP           DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  create_date     DATETIME            DEFAULT NULL,
  i18n_key        VARCHAR(255),
  question_id     BIGINT(20)          DEFAULT NULL,
  choice_id     BIGINT(20)          DEFAULT NULL,
  choice          VARCHAR(255),
  question_legacy_id VARCHAR(255),
  PRIMARY KEY (id)
);

CREATE UNIQUE INDEX locatable_sort_order_Dtype ON locatable (DTYPE, sort_order);
CREATE INDEX locatable_i18n_key_idx ON locatable (i18n_key);
CREATE INDEX parent_index ON locatable (parent_id);
CREATE INDEX DTYPE_index ON locatable (DTYPE);
CREATE INDEX locatable_legacy_idx ON locatable (legacy_id);
CREATE INDEX legacy_choice_choice ON legacy_choice(choice);
CREATE INDEX legacy_choice_question_id ON legacy_choice(question_id);

DROP TABLE IF EXISTS query_performance;
CREATE TABLE query_performance
(
  version   VARCHAR(255),
  type VARCHAR(255),
  rows INT,
  message         VARCHAR(255),
  change_date DATETIME,
  time_diff INT DEFAULT NULL,
  object_id INT
);

DROP TABLE IF EXISTS question_choice_group_name;

CREATE TABLE question_choice_group_name (
  question     VARCHAR(255),
  choice_group VARCHAR(1024)
);

INSERT INTO question_choice_group_name (question, choice_group) VALUES
  ('partner.p_region', 'Regionen'),
  ('freund.f_region', 'Regionen'),
  ('partner.p_land_1', 'Deutschsprachiger Raum'),
  ('partner.p_land_2', 'Deutschsprachiger Raum'),
  ('partner.p_land_3', 'Deutschsprachiger Raum'),
  ('freund.f_land_1', 'Deutschsprachiger Raum'),
  ('freund.f_land_2', 'Deutschsprachiger Raum'),
  ('freund.f_land_3', 'Deutschsprachiger Raum'),
  ('partner.p_radius_1', 'Umkreis'),
  ('partner.p_radius_2', 'Umkreis'),
  ('partner.p_radius_3', 'Umkreis'),
  ('freund.f_radius_1', 'Umkreis'),
  ('freund.f_radius_2', 'Umkreis'),
  ('freund.f_radius_3', 'Umkreis'),
  ('partner.p_oeko_praef', 'Standard-Typus'),
  ('partner.p_eso_praef', 'Standard-Typus'),
  ('partner.p_tierrechte_praef', 'Standard-Typus'),
  ('partner.heiraten', 'Standard-Typus'),
  ('partner.p_fkk_praef', 'Standard-Typus'),
  ('partner.wochenende', 'Standard-Typus'),
  ('partner.umzug', 'Standard-Typus'),
  ('partner.p_akad_suche', 'Standard-Typus'),
  ('partner.p_raucher_akzeptieren', 'Standard-Typus'),
  ('partner.p_kuenstler_suche', 'Standard-Typus'),
  ('partner.p_hochsensibel', 'Standard-Typus'),
  ('partner.p_relsearch_ch', 'Standard-Typus'),
  ('partner.p_relsearch_is', 'Standard-Typus'),
  ('partner.p_relsearch_jud', 'Standard-Typus'),
  ('partner.p_relsearch_bud', 'Standard-Typus'),
  ('partner.p_relsearch_hin', 'Standard-Typus'),
  ('partner.p_relsearch_schin', 'Standard-Typus'),
  ('partner.p_relsearch_bahai', 'Standard-Typus'),
  ('partner.p_relsearch_eso', 'Standard-Typus'),
  ('partner.p_relsearch_agn', 'Standard-Typus'),
  ('partner.p_bisex_suche', 'Wichtigkeit'),
  ('partner.p_transsex_suche', 'Wichtigkeit'),
  ('partner.p_intersex_suche', 'Wichtigkeit'),
  ('partner.p_behinderung', 'Standard-Typus'),
  ('partner.p_behinderung_suche', 'Wichtigkeit'),
  ('partner.p_erkrankung_koer', 'Standard-Typus'),
  ('partner.p_erkrankung_koer_suche', 'Wichtigkeit'),
  ('partner.p_erkrankung_psy', 'Standard-Typus'),
  ('partner.p_erkrankung_psy_suche', 'Wichtigkeit'),
  ('partner.p_hiv', 'Standard-Typus'),
  ('partner.p_hiv_suche', 'Wichtigkeit'),
  ('partner.p_sexfunc', 'Standard-Typus'),
  ('partner.p_sexfunc_suche', 'Wichtigkeit'),
  ('partner.p_gewicht_akzeptieren', 'Standard-Typus'),
  ('partner.p_tierakz_hu', 'Standard-Typus'),
  ('partner.p_tierakz_ka', 'Standard-Typus'),
  ('partner.p_tierakz_na', 'Standard-Typus'),
  ('partner.p_tierakz_pf', 'Standard-Typus'),
  ('partner.p_tierakz_vo', 'Standard-Typus'),
  ('partner.p_tierakz_fi', 'Standard-Typus'),
  ('partner.p_tierakz_re', 'Standard-Typus'),
  ('partner.p_tierakz_in', 'Standard-Typus'),
  ('freund.f_oeko_praef', 'Standard-Typus'),
  ('freund.f_eso_praef', 'Standard-Typus'),
  ('freund.f_tierrechte_praef', 'Standard-Typus'),
  ('freund.f_fkk_praef', 'Standard-Typus'),
  ('freund.f_akad_suche', 'Standard-Typus'),
  ('freund.f_raucher_akzeptieren', 'Standard-Typus'),
  ('freund.f_kuenstler_suche', 'Standard-Typus'),
  ('freund.f_hochsensibel', 'Standard-Typus'),
  ('freund.f_relsearch_ch', 'Standard-Typus'),
  ('freund.f_relsearch_is', 'Standard-Typus'),
  ('freund.f_relsearch_jud', 'Standard-Typus'),
  ('freund.f_relsearch_bud', 'Standard-Typus'),
  ('freund.f_relsearch_hin', 'Standard-Typus'),
  ('freund.f_relsearch_schin', 'Standard-Typus'),
  ('freund.f_relsearch_bahai', 'Standard-Typus'),
  ('freund.f_relsearch_eso', 'Standard-Typus'),
  ('freund.f_relsearch_agn', 'Standard-Typus'),
  ('freund.f_behinderung', 'Standard-Typus'),
  ('freund.f_behinderung_suche', 'Wichtigkeit'),
  ('freund.f_erkrankung_koer', 'Standard-Typus'),
  ('freund.f_erkrankung_koer_suche', 'Wichtigkeit'),
  ('freund.f_erkrankung_psy', 'Standard-Typus'),
  ('freund.f_erkrankung_psy_suche', 'Wichtigkeit'),
  ('freund.f_hiv', 'Standard-Typus'),
  ('freund.f_hiv_suche', 'Wichtigkeit'),
  ('freund.f_tierakz_hu', 'Standard-Typus'),
  ('freund.f_tierakz_ka', 'Standard-Typus'),
  ('freund.f_tierakz_na', 'Standard-Typus'),
  ('freund.f_tierakz_pf', 'Standard-Typus'),
  ('freund.f_tierakz_vo', 'Standard-Typus'),
  ('freund.f_tierakz_fi', 'Standard-Typus'),
  ('freund.f_tierakz_re', 'Standard-Typus'),
  ('freund.f_tierakz_in', 'Standard-Typus'),
  ('person.relprev_ch', 'Standard-Typus'),
  ('person.relprev_is', 'Standard-Typus'),
  ('person.relprev_jud', 'Standard-Typus'),
  ('person.relprev_bud', 'Standard-Typus'),
  ('person.relprev_hin', 'Standard-Typus'),
  ('person.relprev_schin', 'Standard-Typus'),
  ('person.relprev_bahai', 'Standard-Typus'),
  ('person.relprev_eso', 'Standard-Typus'),
  ('person.relprev_agn', 'Standard-Typus'),
  ('partner.p_mr_praef', 'Standard-Typus'),
  ('partner.p_monogam', 'Standard-Typus'),
  ('partner.p_reise_praef', 'Standard-Typus'),
  ('partner.p_auswandern_praef', 'Standard-Typus'),
  ('partner.p_zusleb_praef', 'Standard-Typus'),
  ('partner.p_bildung_praef', 'Standard-Typus'),
  ('partner.p_gesleb_praef', 'Standard-Typus'),
  ('partner.p_polyamor', 'Standard-Typus'),
  ('freund.f_mr_praef', 'Standard-Typus'),
  ('freund.f_auswandern_praef', 'Standard-Typus'),
  ('freund.f_zusleb_praef', 'Standard-Typus'),
  ('freund.f_bildung_praef', 'Standard-Typus'),
  ('freund.f_gesleb_praef', 'Standard-Typus'),
  ('freund.f_polyamor', 'Standard-Typus'),
  ('partner.p_vege_suche', 'Vegetarier'),
  ('partner.p_vegan_suche', 'Vegan'),
  ('freund.f_vege_suche', 'Vegetarier'),
  ('freund.f_vegan_suche', 'Vegan'),
  ('partner.p_dreierbez', 'Spezial-Ausschließlich'),
  ('partner.p_bisex', 'Spezial-Ausschließlich'),
  ('partner.p_transsex', 'Spezial-Ausschließlich'),
  ('partner.p_intersex', 'Spezial-Ausschließlich'),
  ('partner.p_transvestit', 'Spezial-Ausschließlich'),
  ('partner.p_alleinerziehend_select', 'Drei-Stufung (mit unentschieden)'),
  ('freund.f_alleinerziehend_select', 'Drei-Stufung (mit unentschieden)'),
  ('partner.kinderwunsch', 'Kinderwunsch'),
  ('partner.p_erotik', 'Erotik-Abfrage (P)'),
  ('partner.p_sexdev', 'Sex-Bedeutung'),
  ('partner.p_bdsm_suche', 'BDSM-Initial'),
  ('partner.p_bdsm_suche_allg', 'BDSM-Initial'),
  ('freund.f_bdsm_suche', 'BDSM-Initial'),
  ('freund.f_bdsm_suche_allg', 'BDSM-Initial'),
  ('partner.p_platonisch_suche', 'Platonisch'),
  ('partner.p_bdsm_suche_spezial', 'BDSM-Spezial'),
  ('freund.f_bdsm_suche_spezial', 'BDSM-Spezial'),
  ('partner.p_gewicht_ausschluss', 'Figur'),
  ('partner.p_gewicht_wunsch', 'Figur'),
  ('partner.p_akz_fem_mask', 'Feminität'),
  ('freund.f_reise_partner', 'Nein-Auch-Nur'),
  ('freund.f_gay_select', 'Nein-Auch-Nur'),
  ('freund.f_erotik', 'Erotik-Abfrage (F)'),
  ('ptext.frage1', 'Satzanfänge'),
  ('ptext.frage2', 'Satzanfänge'),
  ('ptext.frage3', 'Satzanfänge'),
  ('ftext.frage1', 'Satzanfänge'),
  ('ftext.frage2', 'Satzanfänge'),
  ('ftext.frage3', 'Satzanfänge'),
  ('aussehen.figur', 'Eigene Figur'),
  ('aussehen.koerpertyp', 'Eigener Körpertyp'),
  ('aussehen.haarfarbe', 'Eigene Haarfarbe'),
  ('aussehen.haarlaenge', 'Eigene Haarlänge'),
  ('aussehen.glatze', 'Eigene Glatze'),
  ('aussehen.haartyp', 'Eigener Haartyp'),
  ('aussehen.augenfarbe', 'Eigene Augenfarbe'),
  ('aussehen.brille', 'Eigene Brille'),
  ('aussehen.bart', 'Eigener Bart'),
  ('aussehen.brustbehaarung', 'Eigene Behaarung'),
  ('aussehen.koerperbehaarung', 'Eigene Behaarung'),
  ('aussehen.fem_mask', 'Eigene Feminität/Maskulinität'),
  ('person.schulabschluss', 'Schulabschluss'),
  ('person.berufsausbildung', 'Ausbildung'),
  ('person.beruflicher_status', 'Berufsstatus'),
  ('person.berufsfeld', 'Berufsfeld'),
  ('person.familienstand', 'Familienstand'),
  ('person.kinder_haushalt', 'Drei-Stufung (teils)'),
  ('person.tiere', 'Eigene Tiere'),
  ('person.rauchen', 'Rauchen'),
  ('person.alkoholkonsum', 'Alkohol'),
  ('person.schlafrhythmus', 'Schlafrythmus'),
  ('person.ordnungsliebe', 'Vier-Stufung (ja/nein)'),
  ('person.vege_info', 'Eigen Vegetarismus'),
  ('person.vegan_info', 'Eigen Veganismus'),
  ('person.hochsensibel_info', 'Fünf-Stufung (mit unbekannt)'),
  ('hobby_v.fernsehen', 'Hobby Fernsehen'),
  ('hobby_v.musik_passiv', 'Hobby Musik (passiv)'),
  ('hobby_v.musik_aktiv', 'Hobby Musik (aktiv)'),
  ('hobby_v.bildung', 'Bildungsinteressen'),
  ('hobby_v.computer', 'Hobby Interessen Computer'),
  ('hobby_v.essen_kueche', 'Hobby Essen Küche'),
  ('hobby_v.essen_kost', 'Hobby Essen Kost'),
  ('hobby_v.geselligkeit', 'Hobby Geselligkeit'),
  ('hobby_v.heimwerken', 'Hobby Heimwerken'),
  ('hobby_v.gestaltende_kunst', 'Hobby Gestaltende Kunst'),
  ('hobby_v.darstellende_kunst', 'Hobby Darstellende Kunst'),
  ('hobby_v.foto_film', 'Hobby Foto/Film'),
  ('hobby_v.handarbeit', 'Hobby Handarbeit'),
  ('hobby_v.mode', 'Hobby Mode'),
  ('hobby_v.kulturveranstaltungen', 'Hobby Kulturveranstaltungen'),
  ('hobby_v.spiele', 'Hobby Spiele'),
  ('hobby_v.literatur_gattung', 'Hobby Literatur Gattung'),
  ('hobby_v.literatur_themen', 'Hobby Literatur Themen'),
  ('hobby_v.tanzen', 'Hobby Tanzen'),
  ('hobby_v.gesundheit', 'Hobby Gesundheit'),
  ('hobby_v.sport_aktiv', 'Hobby Sport'),
  ('hobby_v.sport_passiv', 'Hobby Sport'),
  ('hobby_v.technik', 'Hobby Technik'),
  ('hobby_v.tiere_natur', 'Hobby Tiere/Natur'),
  ('hobby_v.extremsport', 'Hobby Extremsport'),
  ('hobby_v.soziales_engagement', 'Hobby Engagement Sozial'),
  ('hobby_v.politisches_engagement', 'Hobby Engagement Politisch'),
  ('hobby_v.kommunikation', 'Hobby Kommunikation'),
  ('hobby_v.sammeln', 'Hobby Sammeln'),
  ('hobby_v.geld', 'Hobby Geld'),
  ('hobby_v.esoterik', 'Hobby Esoterik'),
  ('hobby_v.reisen', 'Hobby Reisen'),
  ('partner.p_hiv_select', 'Ja/Nein'),
  ('partner.p_behinderten_select', 'Ja/Nein'),
  ('partner.p_koerperkrank_select', 'Ja/Nein'),
  ('partner.p_psychischkrank_select', 'Ja/Nein'),
  ('partner.p_nur_foto', 'Ja/Nein'),
  ('partner.p_region_umzug', 'Ja/Nein'),
  ('partner.p_erotik_mitteil', 'Ja/Nein'),
  ('partner.p_bdsm_nur', 'Ja/Nein'),
  ('partner.p_bdsm_mitteil', 'Ja/Nein'),
  ('partner.p_platonisch_mitteil', 'Ja/Nein'),
  ('freund.f_hiv_select', 'Ja/Nein'),
  ('freund.f_behinderten_select', 'Ja/Nein'),
  ('freund.f_koerperkrank_select', 'Ja/Nein'),
  ('freund.f_psychischkrank_select', 'Ja/Nein'),
  ('freund.f_nur_foto', 'Ja/Nein'),
  ('freund.f_gay_mitteil', 'Ja/Nein'),
  ('freund.f_erotik_mitteil', 'Ja/Nein'),
  ('freund.f_bdsm_nur', 'Ja/Nein'),
  ('freund.f_bdsm_mitteil', 'Ja/Nein'),
  ('person.alleinerziehend', 'Ja/Nein'),
  ('person.in_partnerschaft', 'Ja/Nein'),
  ('person.kuenstler', 'Ja/Nein'),
  ('person.transvestit', 'Ja/Nein'),
  ('person.hochsensibel_mitteil', 'Ja/Nein'),
  ('person.rel_mitteil', 'Ja/Nein'),
  ('person.hiv_info', 'Ja/Nein'),
  ('person.behinderten_info', 'Ja/Nein'),
  ('person.koerperkrank_info', 'Ja/Nein'),
  ('person.psychisch_krank_info', 'Ja/Nein'),
  ('stamm.geschlecht', 'Geschlechtsauswahl'),
  ('partner.geschlecht', 'Geschlechtssuche'),
  ('freund.geschlecht', 'Geschlechtssuche'),
  ('partnerschaft.p5_1', 'Affinität'),
  ('partnerschaft.p17_2', 'Affinität'),
  ('partnerschaft.p31_1', 'Affinität'),
  ('partnerschaft.p31_2', 'Affinität'),
  ('partnerschaft.p17_3', 'Affinität'),
  ('partnerschaft.p1_4', 'Affinität'),
  ('partnerschaft.p31_3', 'Affinität'),
  ('partnerschaft.p10_4', 'Affinität'),
  ('partnerschaft.p11_4', 'Affinität'),
  ('partnerschaft.p16_4', 'Affinität'),
  ('partnerschaft.p5_5', 'Affinität'),
  ('partnerschaft.p13_5', 'Affinität'),
  ('partnerschaft.p17_5', 'Affinität'),
  ('partnerschaft.p1_6', 'Affinität'),
  ('partnerschaft.p11_6', 'Affinität'),
  ('partnerschaft.p5_7', 'Affinität'),
  ('partnerschaft.p12_6', 'Affinität'),
  ('partnerschaft.p14_7', 'Affinität'),
  ('partnerschaft.p16_7', 'Affinität'),
  ('partnerschaft.p31_4', 'Affinität'),
  ('partnerschaft.p5_8', 'Affinität'),
  ('partnerschaft.p6_8', 'Affinität'),
  ('partnerschaft.p17_8', 'Affinität'),
  ('partnerschaft.p31_5', 'Affinität'),
  ('partnerschaft.p12_11', 'Affinität'),
  ('gesellschaft.g1_1', 'Affinität'),
  ('gesellschaft.g2_1', 'Affinität'),
  ('gesellschaft.g4_1', 'Affinität'),
  ('gesellschaft.g5_1', 'Affinität'),
  ('gesellschaft.g2_3', 'Affinität'),
  ('gesellschaft.g1_5', 'Affinität'),
  ('gesellschaft.g5_5', 'Affinität'),
  ('gesellschaft.g3_6', 'Affinität'),
  ('gesellschaft.g1_7', 'Affinität'),
  ('gesellschaft.g3_7', 'Affinität'),
  ('gesellschaft.g4_7', 'Affinität'),
  ('gesellschaft.g2_9', 'Affinität'),
  ('gesellschaft.g3_10', 'Affinität'),
  ('gesellschaft.g5_12', 'Affinität'),
  ('gesellschaft.g4_12', 'Affinität'),
  ('persoenlichkeit.pk_36_ve', 'Affinität'),
  ('persoenlichkeit.pk_37_h', 'Affinität'),
  ('persoenlichkeit.pk_38_ge', 'Affinität'),
  ('persoenlichkeit.pk_43_fa', 'Affinität'),
  ('persoenlichkeit.pk_62_r', 'Affinität'),
  ('persoenlichkeit.pk_64_sb', 'Affinität'),
  ('persoenlichkeit.pk_67_h', 'Affinität'),
  ('persoenlichkeit.pk_68_ge', 'Affinität'),
  ('persoenlichkeit.pk_72_pe', 'Affinität'),
  ('persoenlichkeit.pk_77_i', 'Affinität'),
  ('persoenlichkeit.pk_81_al', 'Affinität'),
  ('persoenlichkeit.pk_88_l', 'Affinität'),
  ('persoenlichkeit.pk_91_ae', 'Affinität'),
  ('persoenlichkeit.pk_92_r', 'Affinität'),
  ('persoenlichkeit.pk_104_aes', 'Affinität'),
  ('persoenlichkeit.pk_107_i', 'Affinität'),
  ('persoenlichkeit.pk_119_s', 'Affinität'),
  ('persoenlichkeit.pk_141_al', 'Affinität'),
  ('persoenlichkeit.pk_163_fa', 'Affinität'),
  ('persoenlichkeit.pk_194_aes', 'Affinität'),
  ('persoenlichkeit.pk_209_s', 'Affinität'),
  ('persoenlichkeit.pk_217_h', 'Affinität'),
  ('persoenlichkeit.pk_230_f', 'Affinität'),
  ('persoenlichkeit.pk_262_e', 'Affinität'),
  ('persoenlichkeit.pk_266_ol', 'Affinität'),
  ('persoenlichkeit.pk_269_s', 'Affinität'),
  ('persoenlichkeit.pk_290_f', 'Affinität'),
  ('persoenlichkeit.pk_292_e', 'Affinität'),
  ('persoenlichkeit.pk_299_s', 'Affinität'),
  ('freundschaft.fd_pp106', 'Affinität'),
  ('freundschaft.fd_sf71', 'Affinität'),
  ('freundschaft.fd_nd119', 'Affinität'),
  ('freundschaft.fd_ag42', 'Affinität'),
  ('freundschaft.fd_ag43', 'Affinität'),
  ('freundschaft.fd_ps53', 'Affinität'),
  ('freundschaft.fd_sf76', 'Affinität'),
  ('freundschaft.fd_pp105', 'Affinität'),
  ('freundschaft.fd_ps50', 'Affinität'),
  ('freundschaft.fd_ps46', 'Affinität'),
  ('freundschaft.fd_sf72', 'Affinität'),
  ('freundschaft.fd_sp129', 'Affinität'),
  ('freundschaft.fd_ag35', 'Affinität'),
  ('freundschaft.fd_pp100', 'Affinität'),
  ('freundschaft.fd_pp111', 'Affinität'),
  ('freundschaft.fd_sf62', 'Affinität'),
  ('freundschaft.fd_ps55', 'Affinität'),
  ('freundschaft.fd_ag34', 'Affinität'),
  ('freundschaft.fd_sp127', 'Affinität'),
  ('freundschaft.fd_ag39', 'Affinität'),
  ('freundschaft.fd_sp130', 'Affinität'),
  ('source', 'Quellen');

