ALTER TABLE news MODIFY title VARCHAR(255) NOT NULL;
ALTER TABLE news MODIFY teaser_text TEXT NOT NULL;
ALTER TABLE news MODIFY text TEXT NOT NULL;
ALTER TABLE news MODIFY valid_from DATETIME NOT NULL;
ALTER TABLE news MODIFY valid_to DATETIME NOT NULL;
ALTER TABLE news MODIFY language VARCHAR(255) NOT NULL;