-- drop comp tables
DROP TABLE IF EXISTS compadjektive;
DROP TABLE IF EXISTS compadportalrecipient;
DROP TABLE IF EXISTS compaffiliate_promotion;
DROP TABLE IF EXISTS compaffiliate_promotion_refund;
DROP TABLE IF EXISTS compaussehen;
DROP TABLE IF EXISTS compcircularletter;
DROP TABLE IF EXISTS compext_adjektive;
DROP TABLE IF EXISTS compext_freundschaft;
DROP TABLE IF EXISTS compext_gesellschaft;
DROP TABLE IF EXISTS compext_hobby_e;
DROP TABLE IF EXISTS compext_kritische_lebensereignisse;
DROP TABLE IF EXISTS compext_partnerschaft;
DROP TABLE IF EXISTS compext_persoenlichkeit;
DROP TABLE IF EXISTS compext_stoerbar;
DROP TABLE IF EXISTS compext_stoerbarkeit;
DROP TABLE IF EXISTS compffoto;
DROP TABLE IF EXISTS compfreund;
DROP TABLE IF EXISTS compfreundschaft;
DROP TABLE IF EXISTS compftext;
DROP TABLE IF EXISTS compgesellschaft;
DROP TABLE IF EXISTS comphobby_e;
DROP TABLE IF EXISTS comphobby_v;
DROP TABLE IF EXISTS compkritische_lebensereignisse;
DROP TABLE IF EXISTS complinkentry;
DROP TABLE IF EXISTS compmail_additionaldata;
DROP TABLE IF EXISTS compmail_atomcondition;
DROP TABLE IF EXISTS compmail_campaign;
DROP TABLE IF EXISTS compmail_campaign_category;
DROP TABLE IF EXISTS compmail_category;
DROP TABLE IF EXISTS compmail_category_condlist;
DROP TABLE IF EXISTS compmail_conditionlist;
DROP TABLE IF EXISTS compmail_condlist_atomcond;
DROP TABLE IF EXISTS compmail_dataentry;
DROP TABLE IF EXISTS compmatch_pair;
DROP TABLE IF EXISTS compmatch_pair_info;
DROP TABLE IF EXISTS compmatch_participant_info;
DROP TABLE IF EXISTS compmatch_searchdomain_info;
DROP TABLE IF EXISTS compmatch_select_info;
DROP TABLE IF EXISTS compmatch_statistic_info;
DROP TABLE IF EXISTS compmedium;
DROP TABLE IF EXISTS compmessage;
DROP TABLE IF EXISTS compnews;
DROP TABLE IF EXISTS compnewsletterrecipient;
DROP TABLE IF EXISTS compnewsread;
DROP TABLE IF EXISTS comppartner;
DROP TABLE IF EXISTS comppartnerschaft;
DROP TABLE IF EXISTS comppayment_bill;
DROP TABLE IF EXISTS comppayment_break;
DROP TABLE IF EXISTS comppayment_event;
DROP TABLE IF EXISTS comppayment_offer;
DROP TABLE IF EXISTS comppayment_rate;
DROP TABLE IF EXISTS comppayment_transaction;
DROP TABLE IF EXISTS comppayment_userinfo;
DROP TABLE IF EXISTS comppersoenlichkeit;
DROP TABLE IF EXISTS compperson;
DROP TABLE IF EXISTS comppfoto;
DROP TABLE IF EXISTS compphonenumber;
DROP TABLE IF EXISTS compplzlist;
DROP TABLE IF EXISTS compproband_socio_economics;
DROP TABLE IF EXISTS compptext;
DROP TABLE IF EXISTS compregion_addresslocation;
DROP TABLE IF EXISTS compregion_adresslocation;
DROP TABLE IF EXISTS compregion_assignment;
DROP TABLE IF EXISTS compregion_basesearch;
DROP TABLE IF EXISTS compregion_geonameszip;
DROP TABLE IF EXISTS compregion_searchrestr;
DROP TABLE IF EXISTS compstoerbar;
DROP TABLE IF EXISTS compsymbol;
DROP TABLE IF EXISTS compteilnehmerfilterinfo;
DROP TABLE IF EXISTS compundeliveredmail;
DROP TABLE IF EXISTS compunsolicitedmail;
DROP TABLE IF EXISTS compuser;
DROP TABLE IF EXISTS compuseractivity;
DROP TABLE IF EXISTS compvorschlag;
DROP TABLE IF EXISTS compziparea;
DROP TABLE IF EXISTS compzipcity;

-- drop old helper tables
DROP TABLE IF EXISTS intersex_user;
DROP TABLE IF EXISTS legacy_choice;

-- remove legacy columns
CALL DROP_COLUMN('activator', 'legacy_id');
CALL DROP_COLUMN('address', 'legacy_id');
CALL DROP_COLUMN('admin_user_login', 'legacy_id');
CALL DROP_COLUMN('admin_work_item', 'legacy_id');
CALL DROP_COLUMN('affiliate_payment_state', 'legacy_id');
CALL DROP_COLUMN('answer', 'legacy_id');
CALL DROP_COLUMN('area_match_statistic_entry', 'legacy_id');
CALL DROP_COLUMN('avatar', 'legacy_id');
CALL DROP_COLUMN('bank_account', 'legacy_id');
CALL DROP_COLUMN('cache', 'legacy_id');
CALL DROP_COLUMN('choice', 'legacy_id');
CALL DROP_COLUMN('choice_answer', 'legacy_id');
CALL DROP_COLUMN('choice_group', 'legacy_id');
CALL DROP_COLUMN('client_information', 'legacy_id');
CALL DROP_COLUMN('email_link', 'legacy_id');
CALL DROP_COLUMN('email_link_parameter', 'legacy_id');
CALL DROP_COLUMN('envelope', 'legacy_id');
CALL DROP_COLUMN('external_payment_registration', 'legacy_id');
CALL DROP_COLUMN('file', 'legacy_id');
CALL DROP_COLUMN('filter', 'legacy_id');
CALL DROP_COLUMN('heidelpay_transaction', 'legacy_id');
CALL DROP_COLUMN('i18n', 'legacy_id');
CALL DROP_COLUMN('invoice', 'legacy_id');
CALL DROP_COLUMN('invoice_item', 'legacy_id');
CALL DROP_COLUMN('locatable', 'legacy_id');
CALL DROP_COLUMN('mail_queue_entry', 'legacy_id');
CALL DROP_COLUMN('match_', 'legacy_id');
CALL DROP_COLUMN('match_statistic', 'legacy_id');
CALL DROP_COLUMN('match_statistic_entry', 'legacy_id');
CALL DROP_COLUMN('matching_matrix', 'legacy_id');
CALL DROP_COLUMN('matching_matrix_value', 'legacy_id');
CALL DROP_COLUMN('media', 'legacy_id');
CALL DROP_COLUMN('media_gallery', 'legacy_id');
CALL DROP_COLUMN('message', 'legacy_id');
CALL DROP_COLUMN('message_attachment', 'legacy_id');
CALL DROP_COLUMN('news', 'legacy_id');
CALL DROP_COLUMN('payment', 'legacy_id');
CALL DROP_COLUMN('product', 'legacy_id');
CALL DROP_COLUMN('proximity_search_request', 'legacy_id');
CALL DROP_COLUMN('question', 'legacy_id');
CALL DROP_COLUMN('question_group', 'legacy_id');
CALL DROP_COLUMN('questionnaire', 'legacy_id');
CALL DROP_COLUMN('questions_mapping', 'legacy_id');
CALL DROP_COLUMN('recommendation_break', 'legacy_id');
CALL DROP_COLUMN('region_search_request', 'legacy_id');
CALL DROP_COLUMN('relationship', 'legacy_id');
CALL DROP_COLUMN('service_offer_category', 'legacy_id');
CALL DROP_COLUMN('subscription', 'legacy_id');
CALL DROP_COLUMN('subscription_offer_category', 'legacy_id');
CALL DROP_COLUMN('undeliverable_mail', 'legacy_id');
CALL DROP_COLUMN('user_', 'legacy_id');
CALL DROP_COLUMN('user_activity_log', 'legacy_id');
CALL DROP_COLUMN('user_news', 'legacy_id');
CALL DROP_COLUMN('user_payment_settings', 'legacy_id');
CALL DROP_COLUMN('user_registration_state', 'legacy_id');
CALL DROP_COLUMN('user_settings', 'legacy_id');