ALTER TABLE user_
ADD COLUMN cust_id VARCHAR(255),
ADD COLUMN card_id VARCHAR(255);
ALTER TABLE payment
ADD COLUMN charge_id VARCHAR(255),
ADD COLUMN payment_id VARCHAR(255),
ADD COLUMN auth_id VARCHAR(255);