# properties for robhost
app.theme=gk_theme

#file.path=/home/dev-gleichklang/persisted-user-files
file.path=/opt/tomcat/webapps/files
file_audio_path=/opt/tomcat/webapps/files/audio

db.auto.flyway.repair=false

server.base_url=https://gleichklang.de/dev/Gleichklang/
heidelpay.frontend.response_url=https://gleichklang.de/dev/Gleichklang/api/heidelpay/response
heidelpay.transaction.channel=31HA07BC8124B0DD41FE4DACD35C8F35
converter_path=https://online-audio-converter.com/de/

heidelpay.frontend.css_path=https://gleichklang.de/dev/Gleichklang/VAADIN/themes/gk_theme/heidelpay_hco.css
heidelpay.frontend.jscript_path=https://gleichklang.de/dev/Gleichklang/VAADIN/themes/gk_theme/heidelpay_hco.js

heidelpay.ignore_host_id=true

email.server=imaps://www.gleichklang-mail.de:587
email.user=softwaretest-01@gleichklang.de
email.password=Enukodisa960
email.sender=softwaretest-01@gleichklang.de
email.max_attempts=5
email.undeliverable_mail.scheduler_enabled=true

email.gk_social.server=imaps://@www.gleichklang-mail.de:587
email.gk_social.user=softwaretest-02@gleichklang.de
email.gk_social.password=Inogeriwe522
email.gk_social.scheduler_enabled=true

login.default.username=
login.default.password=

# custom js file URL
custom_js_file=https://gleichklang.de/tnstatic/js/devgk.js?

# Show Affiliate Tracking alert box
affiliate_tracking.alert=true
landing.root=https://www.gleichklang.de/dev/Gleichklang

server.ui.host=gleichklang.de/staging/Gleichklang