# properties for robhost
app.theme=gk_theme

#file.path=/home/dev-gleichklang/persisted-user-files
file.path=/opt/tomcat/webapps/files
file_audio_path=/opt/tomcat/webapps/files

db.auto.flyway.repair=false

db.jdbc.url=jdbc:mysql://127.0.0.1:3308/gleichklang?useUnicode=true&characterEncoding=UTF-8&rewriteBatchedStatements=true&useSSL=false&serverTimezone=Europe/Berlin
db.user=gleichklang
db.password=gleichklang

heidelpay.frontend.response_url=https://gleichklang.de/staging/Gleichklang/api/heidelpay/response
heidelpay.transaction.channel=31HA07BC811DC0574ACBA41EC8707D35
converter_path=https://online-audio-converter.com/de/

heidelpay.frontend.css_path=https://gleichklang.de/staging/Gleichklang/VAADIN/themes/gk_theme/heidelpay_hco.css
heidelpay.frontend.jscript_path=https://gleichklang.de/staging/Gleichklang/VAADIN/themes/gk_theme/heidelpay_hco.js

heidelpay.ignore_host_id=true

email.server=imaps://www.gleichklang-mail.de:587
email.user=softwaretest-05@gleichklang.de
email.password=R_%HTN~q
email.sender=softwaretest-01@gleichklang.de
email.max_attempts=5
email.undeliverable_mail.scheduler_enabled=true

email.gk_social.server=imaps://@www.gleichklang-mail.de:587
email.gk_social.user=softwaretest-06@gleichklang.de
email.gk_social.password=VxNK5[Xq
email.gk_social.scheduler_enabled=true

login.default.username=
login.default.password=

server.ui.host=gleichklang.eu
server.base_url=https://gleichklang.de/staging/Gleichklang/api/

