# properties for robhost

#
# Database
#
db.jdbc.url=jdbc:mysql://localhost:3306/gleichklang?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8
# db.jdbc.url=jdbc:mysql://192.168.35.20:3306/gleichklang?useUnicode=true&characterEncoding=UTF-8&logger=com.mysql.jdbc.log.Slf4JLogger&logSlowQueries=true&explainSlowQueries=false&slowQueryThresholdMillis=1000&rewriteBatchedStatements=true
db.auto.flyway.repair=false

#
# External Payment
#

heidelpay.hco.url=https://heidelpay.hpcgw.net/sgw/gtwu
heidelpay.query.url=https://heidelpay.hpcgw.net/TransactionCore/xml

heidelpay.security.sender=8a90948c0b6f3063010b8408fa2d1402
heidelpay.user.login=8a90948c0b6f3063010b84093e0b1404
heidelpay.user.pwd=7aya5yYs

heidelpay.transaction.channel=8a90948c0b6f3063010b840dd8721422
heidelpay.transaction.mode=LIVE

heidelpay.frontend.response_url=https://gleichklang.de/teilnehmer/api/heidelpay/response
heidelpay.frontend.css_path=https://gleichklang.de/teilnehmer/VAADIN/themes/gk_theme/heidelpay_hco.css
heidelpay.frontend.jscript_path=https://gleichklang.de/teilnehmer/VAADIN/themes/gk_theme/heidelpay_hco.js

heidelpay.ignore_host_id=true

#
# File Handling
#

file.path=/mnt/webapps/files
file_audio_path=/mnt/webapps/files/audio

#
# Emails
#

server.base_url=https://gleichklang.de/teilnehmer/
converter_path=https://online-audio-converter.com/de/

email.server=imaps://www.gleichklang-mail.de:587
email.user=kommunikation@gleichklang.de
email.password=]fDpArUb
email.sender=kommunikation@gleichklang.de
email.max_attempts=5
email.undeliverable_mail.scheduler_enabled=true
email.white_list.enabled=false
email.short_reminder_interval=false

email.gk_social.server=imaps://@www.gleichklang-mail.de:587
email.gk_social.user=sozial@gleichklang.de
email.gk_social.password=PkfW)B4B
email.gk_social.scheduler_enabled=true

external.links.root=https://www.gleichklang.de
landing.root=https://www.gleichklang.de

login.default.username=
login.default.password=

affiliate_tracking.alert=false

#CronJob enabled -> hide Buttons
matching.auto.enabled=true

# custom js file URL
custom_js_file=https://gleichklang.de/tnstatic/js/gk.js?

#languageselection
language.selection.activated=false

export_coronovirus_msg=https://gleichklang.de/teilnehmer/VAADIN/pdf/directlist.pdf