# UI Theme
app.theme=gk_theme
server.ui.host=gleichklang.web.n1.iworklab.com
# comma separated list of all allowed origins
cors.allowed.origins=*
session.timeout=5
# database properties

# db.jdbc.url=jdbc:mysql://localhost:3306/gleichklang_development?useUnicode=true&characterEncoding=UTF-8&rewriteBatchedStatements=true&useSSL=false
# db.user=gleichklang_development
# db.password=gleichklang_development

db.jdbc.url=jdbc:mysql://localhost:3306/gleichklang?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8
db.user=gleichklang
db.password=gleichklang

db.connection.pool.max.active=100
db.connection.pool.max.idle=100
db.connection.pool.remove.abandoned.timeout=86400

db.auto.flyway.repair=false

#
# External payments
#
VnvTM@#2019#@#
heidelpay.hco.url=https://test-heidelpay.hpcgw.net/sgw/gtwu
heidelpay.query.url=https://test-heidelpay.hpcgw.net/TransactionCore/xml

heidelpay.security.sender=31HA07BC810B08B9E9B67424BE1C97D9

heidelpay.user.login=31ha07bc810b08b9e9b6a7a910e32485
heidelpay.user.pwd=11F6BAB0

heidelpay.transaction.channel=31HA07BC810B08B9E9B67603E697CCF5
heidelpay.transaction.mode=CONNECTOR_TEST

# this url contains the canonical host name to allow our reverse proxy to proxy
# the incoming heidelpay request to the host that send the initial request
heidelpay.frontend.response_url=https://87.139.190.159/${host.hostName}/Gleichklang/rest/heidelpay/response

heidelpay.frontend.css_path=https://87.139.190.159/${host.hostName}/Gleichklang/VAADIN/themes/gk_theme/heidelpay_hco.css
heidelpay.frontend.jscript_path=https://87.139.190.159/${host.hostName}/Gleichklang/VAADIN/themes/gk_theme/heidelpay_hco.js

regional_search.regional_search_limit=10
regional_search.proximity_search_limit=10

# the maximum number of synchronization to perform for external payments
payment.external_payment_max_synchronizations=5

heidelpay.ignore_host_id=false

gleichklang.app.jwtSecret=jwtgleichklangSecretKey
gleichklang.app.jwtExpiration=86400
#
# File Handling
#
file.path=/opt/tomcat8/webapps/files/
file.clamav.url=127.0.0.1
file.clamav.port=3310
file.clamav.timeout=2000
file_audio_path=/opt/tomcat8/webapps/files/
image_blog_path=/opt/tomcat8/webapps/files/blog
server.base_url=https://n3.iworklab.com:8444/Gleichklang/
image.base_url=https://n3.iworklab.com:8444/Gleichklang/VAADIN/themes/gk_theme/
image.base_path=/opt/tomcat8/webapps/Gleichklang/VAADIN/themes/gk_theme/img/
static.image.base_path=/opt/tomcat8/webapps/Gleichklang/VAADIN/static-images

static.images_path=/opt/tomcat8/webapps/Gleichklang/VAADIN/

converter_path=https://online-audio-converter.com/de/

#
# Emails
#
email.server=imaps://www.gleichklang-mail.de:587
email.user=softwaretest-01@gleichklang.de
email.password=Enukodisa960
email.sender=softwaretest-01@gleichklang.de
email.max_attempts=5
email.undeliverable_mail.scheduler_enabled=false
email.white_list.enabled=true
email.short_reminder_interval=true

email.gk_social.server=imaps://mail.binaere-bauten.de:587
email.gk_social.user=gsozial
email.gk_social.password=VQ0uwkW6
email.gk_social.scheduler_enabled=false

#todo security.salt & external.links.root can be removed
security.salt=DLdtu6sxta6UQv
external.links.root=http://basteln.gleichklang.de


subscription_expiration_period_in_days=14
subscription_revocation_period_in_days=14

#logging.level.org.springframework.data=TRACE
#logging.level.org.hibernate=TRACE

# *** It will not be overridden with other property files ***
disable-xsrf-protection=true

login.default.username=valid1@example.com
login.default.password=secret


# Show Affiliate Tracking alert box
affiliate_tracking.alert=false

#CronJob enabled -> hide Buttons
matching.auto.enabled=false

#lovescammingdetection
scamming.message.count=5
scamming.message.duration=180
scamming.contains.mail=true
scamming.keywords=afrika, africa, investment, kredit, credit

#languageselection
language.selection.activated=true

#db driven template enabled
db.driven.template.enabled=true
landing.root=https://n3.iworklab.com:8444/Gleichklang
