# database properties for manual qa test

# db.jdbc.url=jdbc:mysql://mysql0.core.binaere-bauten.de:3306/gleichklang_qa?useUnicode=true&characterEncoding=UTF-8&logger=com.mysql.jdbc.log.Slf4JLogger&logSlowQueries=true&explainSlowQueries=false&slowQueryThresholdMillis=200&rewriteBatchedStatements=true
# db.user=gleichklang
# db.password=gleichklang

db.jdbc.url=jdbc:mysql://localhost:3306/gleichklang?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8
db.user=gleichklang
db.password=gleichklang

db.auto.flyway.repair=true

# this url contains the canonical host name to allow our reverse proxy to proxy
# the incoming heidelpay request to the host that send the initial request
heidelpay.frontend.response_url=https://87.139.190.159/tomcat0.core.binaere-bauten.de/Gleichklang/api/heidelpay/response

heidelpay.frontend.css_path=https://87.139.190.159/tomcat0.core.binaere-bauten.de/Gleichklang/VAADIN/themes/gk_theme/heidelpay_hco.css
heidelpay.frontend.jscript_path=https://87.139.190.159/tomcat0.core.binaere-bauten.de/Gleichklang/VAADIN/themes/gk_theme/heidelpay_hco.js


# file handling
file.path=/opt/tomcat/webapps/files
file_audio_path=/opt/tomcat/webapps/files/audio

server.base_url=http://tomcat0.core.binaere-bauten.de:8080/Gleichklang/
converter_path=https://online-audio-converter.com/de/

email.scheduler_enabled=true
email.gk_social.scheduler_enabled=true

server.ui.host=gleichklang.web.n1.iworklab.com

paypal.mode=sandbox
paypal.client.id=AWejDug8E_pwqI_Zx2B3TqiojFtd1xPx3iweQtwjaFYSOyKO5VOljl3UUdpeFiQo6520X2tc22QHvN1z
paypal.client.secret=EINO_BDmjh9WkPaa0-FzvNjuHMR6jxVeF2Quj9hFA1TKG0BcwDZ6oIfB-3VOP3N6IT6c5P62FsQJfSMu

unzer.api.public.key=s-pub-2a109DDtCqTxQIgd9pRgvQYH5uLeyHls
unzer.api.private.key= s-priv-2a103bxlnRplROGi7VYuz1QsfvNya2by