# database properties for integration test

db.jdbc.url=jdbc:mysql://mysql0.core.binaere-bauten.de:3306/gleichklang_integration?useUnicode=true&characterEncoding=UTF-8
db.user=gleichklang
db.password=gleichklang

