file_audio_path=/opt/tomcat/webapps/files
converter_path=https://online-audio-converter.com/de/

external_mail_host=www.gleichklang-mail.de
external_mail_user=softwaretest-03@gleichklang.de
external_mail_password=Okaromobi124
external_mail_protocol=imap
external_mail_folder=INBOX
external_mail_cache_count=50