# database properties
file.path=gk
jdbc.url=jdbc:mysql://localhost:3306/

db.jdbc.url=jdbc:mysql://localhost:3306/gleichklang_h2_schema_export
# the following entry must match the db.jdbc.url from above
db.database=gleichklang_h2_schema_export

db.user=root1
db.password=root1
