# database properties
file.path=gk
jdbc.url=jdbc:mysql://localhost:3306/

db.jdbc.url=jdbc:mysql://localhost:3306/gleichklang_h2_schema_export?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8
db.database=gleichklang_h2_schema_export

db.user=gleichklang
db.password=gleichklang